using System.Text.Json;
using CSharpDB.Client.Models;

namespace CSharpDB.Client.Grpc;

public sealed record TableNameRequest(string TableName);
public sealed record NameRequest(string Name);
public sealed record PagedTableRequest(string TableName, int Page = 1, int PageSize = 50);
public sealed record PagedNameRequest(string Name, int Page = 1, int PageSize = 50);
public sealed record GetRowByPkRequest(string TableName, string PkColumn, object? PkValue);
public sealed record InsertRowRequest(string TableName, Dictionary<string, object?> Values);
public sealed record UpdateRowRequest(string TableName, string PkColumn, object? PkValue, Dictionary<string, object?> Values);
public sealed record DeleteRowRequest(string TableName, string PkColumn, object? PkValue);
public sealed record RenameTableRequest(string TableName, string NewTableName);
public sealed record AddColumnRequest(string TableName, string ColumnName, DbType Type, bool NotNull);
public sealed record DropColumnRequest(string TableName, string ColumnName);
public sealed record RenameColumnRequest(string TableName, string OldColumnName, string NewColumnName);
public sealed record CreateIndexRequest(string IndexName, string TableName, string ColumnName, bool IsUnique);
public sealed record UpdateIndexRequest(string ExistingIndexName, string NewIndexName, string TableName, string ColumnName, bool IsUnique);
public sealed record CreateViewRequest(string ViewName, string SelectSql);
public sealed record UpdateViewRequest(string ExistingViewName, string NewViewName, string SelectSql);
public sealed record CreateTriggerRequest(string TriggerName, string TableName, TriggerTiming Timing, TriggerEvent TriggerEvent, string BodySql);
public sealed record UpdateTriggerRequest(string ExistingTriggerName, string NewTriggerName, string TableName, TriggerTiming Timing, TriggerEvent TriggerEvent, string BodySql);
public sealed record UpsertSavedQueryRequest(string Name, string SqlText);
public sealed record GetProceduresRequest(bool IncludeDisabled = true);
public sealed record CreateProcedureRequest(ProcedureDefinition Definition);
public sealed record UpdateProcedureRequest(string ExistingName, ProcedureDefinition Definition);
public sealed record ExecuteProcedureRequest(string Name, Dictionary<string, object?> Args);
public sealed record SqlRequest(string Sql);
public sealed record TransactionSqlRequest(string TransactionId, string Sql);
public sealed record TransactionIdRequest(string TransactionId);
public sealed record CollectionNameRequest(string CollectionName);
public sealed record GetDocumentRequest(string CollectionName, string Key);
public sealed record PutDocumentRequest(string CollectionName, string Key, JsonElement Document);
public sealed record DeleteDocumentRequest(string CollectionName, string Key);
public sealed record InspectStorageRequest(string? DatabasePath = null, bool IncludePages = false);
public sealed record CheckWalRequest(string? DatabasePath = null);
public sealed record InspectPageRequest(uint PageId, bool IncludeHex = false, string? DatabasePath = null);
public sealed record CheckIndexesRequest(string? DatabasePath = null, string? IndexName = null, int? SampleSize = null);
