namespace CSharpDB.Migration.Canonicalization;

/// <summary>
/// Stable logical type tags in the <c>csharpdb-canon-v1</c> wire contract.
/// </summary>
public enum CanonicalType : byte
{
    Boolean = 0x01,
    Int64 = 0x02,
    UInt64 = 0x03,
    Decimal = 0x04,
    Binary32 = 0x05,
    Binary64 = 0x06,
    Text = 0x07,
    Blob = 0x08,
    Guid = 0x09,
    Date = 0x0A,
    Time = 0x0B,
    WallDateTime = 0x0C,
    UtcInstant = 0x0D,
    OffsetDateTime = 0x0E,
}

/// <summary>
/// Stable field states in the <c>csharpdb-canon-v1</c> wire contract.
/// </summary>
public enum CanonicalFieldState : byte
{
    Value = 0x00,
    Null = 0x01,
    Excluded = 0x02,
}

/// <summary>
/// Registered reasons for excluding a logical field from equality validation.
/// </summary>
public enum CanonicalExclusionReason : byte
{
    /// <summary>
    /// A BLOB rowversion is regenerated by the target and therefore has no
    /// source/target byte-equality requirement.
    /// </summary>
    RegeneratedRowVersion = 0x01,
}
