[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$manifestPath = Join-Path $repoRoot 'docs/ef-core-compatibility.json'
$schemaPath = Join-Path $repoRoot 'docs/ef-core-compatibility.schema.json'
$outputPath = Join-Path $repoRoot 'docs/ef-core-compatibility.md'
$testRoot = Join-Path $repoRoot 'tests/CSharpDB.EntityFrameworkCore.Tests'

foreach ($requiredPath in @($manifestPath, $schemaPath, $testRoot)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Required EF Core compatibility input is missing: $requiredPath"
    }
}

$manifestJson = [IO.File]::ReadAllText($manifestPath)
$schemaJson = [IO.File]::ReadAllText($schemaPath)
if (-not ($manifestJson | Test-Json -Schema $schemaJson -ErrorAction Stop)) {
    throw "EF Core compatibility manifest does not satisfy $schemaPath."
}
$manifest = $manifestJson | ConvertFrom-Json -Depth 100
$validStatuses = @('Supported', 'Partial', 'Unsupported', 'Planned')
$validTiers = @('tier1', 'tier2', 'tier3')
$ids = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$testSource = (Get-ChildItem -LiteralPath $testRoot -File -Filter '*.cs' |
    ForEach-Object { [IO.File]::ReadAllText($_.FullName) }) -join "`n"

foreach ($feature in @($manifest.features)) {
    $id = [string]$feature.id
    if (-not $ids.Add($id)) {
        throw "Duplicate EF Core compatibility feature id: $id"
    }
    if ([string]$feature.status -notin $validStatuses) {
        throw "Feature '$id' has invalid status '$($feature.status)'."
    }
    if ([string]$feature.tier -notin $validTiers) {
        throw "Feature '$id' has invalid tier '$($feature.tier)'."
    }
    if ([string]$feature.status -eq 'Supported' -and @($feature.proofTests).Count -eq 0) {
        throw "Supported feature '$id' must reference at least one proof test."
    }
    foreach ($proofTest in @($feature.proofTests)) {
        $escapedName = [regex]::Escape([string]$proofTest)
        if (-not [regex]::IsMatch($testSource, "\b$escapedName\s*\(")) {
            throw "Feature '$id' references missing provider test '$proofTest'."
        }
    }
}

function Escape-MarkdownCell {
    param([AllowNull()][object]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return ([string]$Value).Replace('|', '\|').Replace("`r", '').Replace("`n", ' ')
}

$builder = [Text.StringBuilder]::new(32768)
[void]$builder.AppendLine('# EF Core Compatibility')
[void]$builder.AppendLine()
[void]$builder.AppendLine('> Generated from `ef-core-compatibility.json`. Do not edit this file directly.')
[void]$builder.AppendLine()
[void]$builder.AppendLine("Provider: ``$($manifest.provider)``")
[void]$builder.AppendLine()
[void]$builder.AppendLine("Qualified EF Core version: ``$($manifest.efCoreVersion)``")
[void]$builder.AppendLine()
[void]$builder.AppendLine('Statuses describe the current provider behavior. A planned feature is not available merely because it has a Tier 1 priority.')
[void]$builder.AppendLine()
[void]$builder.AppendLine('## Support tiers')
[void]$builder.AppendLine()
foreach ($tier in $validTiers) {
    [void]$builder.AppendLine("- **$tier** — $($manifest.tiers.$tier)")
}

$features = @($manifest.features | Sort-Object category, name, id)
foreach ($category in @($features.category | Sort-Object -Unique)) {
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("## $category")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine('| Feature | Status | Tier | Contract | Proof tests |')
    [void]$builder.AppendLine('| --- | --- | --- | --- | --- |')
    foreach ($feature in @($features | Where-Object category -eq $category)) {
        $proofs = if (@($feature.proofTests).Count -eq 0) { '—' } else { @($feature.proofTests) -join ', ' }
        [void]$builder.AppendLine("| $(Escape-MarkdownCell $feature.name) | $($feature.status) | $($feature.tier) | $(Escape-MarkdownCell $feature.summary) | $(Escape-MarkdownCell $proofs) |")
    }
}

[void]$builder.AppendLine()
[void]$builder.AppendLine("Manifest rows: $($features.Count).")
$generated = $builder.ToString().Replace("`r`n", "`n")

if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPath -PathType Leaf)) {
        throw "Generated EF Core compatibility document is missing. Run scripts/Build-EfCoreCompatibility.ps1."
    }
    $existing = [IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n")
    if (-not [string]::Equals($existing, $generated, [StringComparison]::Ordinal)) {
        throw "Generated EF Core compatibility document is stale. Run scripts/Build-EfCoreCompatibility.ps1."
    }
    Write-Host "EF Core compatibility document is current ($($features.Count) feature rows)."
    return
}

[IO.File]::WriteAllText($outputPath, $generated, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $outputPath from $manifestPath ($($features.Count) feature rows)."
