[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$manifestPath = Join-Path $repoRoot 'docs/ef-core-compatibility.json'
$schemaPath = Join-Path $repoRoot 'docs/ef-core-compatibility.schema.json'
$markdownOutputPath = Join-Path $repoRoot 'docs/ef-core-compatibility.md'
$htmlOutputPath = Join-Path $repoRoot 'www/docs/ef-core-compatibility.html'
$testRoot = Join-Path $repoRoot 'tests/CSharpDB.EntityFrameworkCore.Tests'

foreach ($requiredPath in @($manifestPath, $schemaPath, $testRoot, (Split-Path $htmlOutputPath -Parent))) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Required EF Core compatibility input is missing: $requiredPath"
    }
}

$manifestJson = [IO.File]::ReadAllText($manifestPath)
$schemaJson = [IO.File]::ReadAllText($schemaPath)
if (-not ($manifestJson | Test-Json -Schema $schemaJson -ErrorAction Stop)) {
    throw "EF Core compatibility manifest does not satisfy $schemaPath."
}
$manifest = $manifestJson | ConvertFrom-Json -Depth 100
$validStatuses = @('Supported', 'Partial', 'Unsupported', 'Planned')
$validTiers = @('tier1', 'tier2', 'tier3')
$ids = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$testSource = (Get-ChildItem -LiteralPath $testRoot -File -Filter '*.cs' |
    ForEach-Object { [IO.File]::ReadAllText($_.FullName) }) -join "`n"

foreach ($feature in @($manifest.features)) {
    $id = [string]$feature.id
    if (-not $ids.Add($id)) {
        throw "Duplicate EF Core compatibility feature id: $id"
    }
    if ([string]$feature.status -notin $validStatuses) {
        throw "Feature '$id' has invalid status '$($feature.status)'."
    }
    if ([string]$feature.tier -notin $validTiers) {
        throw "Feature '$id' has invalid tier '$($feature.tier)'."
    }
    if ([string]$feature.status -eq 'Supported' -and @($feature.proofTests).Count -eq 0) {
        throw "Supported feature '$id' must reference at least one proof test."
    }
    foreach ($proofTest in @($feature.proofTests)) {
        $escapedName = [regex]::Escape([string]$proofTest)
        if (-not [regex]::IsMatch($testSource, "\b$escapedName\s*\(")) {
            throw "Feature '$id' references missing provider test '$proofTest'."
        }
    }
}

function Escape-MarkdownCell {
    param([AllowNull()][object]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return ([string]$Value).Replace('|', '\|').Replace("`r", '').Replace("`n", ' ')
}

function ConvertTo-HtmlText {
    param([AllowNull()][object]$Value)

    if ($null -eq $Value) {
        return ''
    }
    return [Net.WebUtility]::HtmlEncode([string]$Value)
}

function ConvertTo-CssToken {
    param([Parameter(Mandatory)][string]$Value)

    return ($Value -replace '[^a-zA-Z0-9_-]', '-').ToLowerInvariant()
}

function Add-HtmlLine {
    param(
        [Parameter(Mandatory)][Text.StringBuilder]$Builder,
        [AllowEmptyString()][string]$Text = ''
    )

    [void]$Builder.Append($Text)
    [void]$Builder.Append("`n")
}

$markdownBuilder = [Text.StringBuilder]::new(32768)
[void]$markdownBuilder.AppendLine('# EF Core Compatibility')
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine('> Generated from `ef-core-compatibility.json`. Do not edit this file directly.')
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine("Provider: ``$($manifest.provider)``")
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine("Qualified EF Core version: ``$($manifest.efCoreVersion)``")
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine("Maturity designation: **$(Escape-MarkdownCell $manifest.maturity.designation)**")
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine("$(Escape-MarkdownCell $manifest.maturity.scope) $(Escape-MarkdownCell $manifest.maturity.tier2Policy) $(Escape-MarkdownCell $manifest.maturity.tier3Policy)")
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine('Statuses describe the current provider behavior. A planned feature is not available merely because it has a Tier 1 priority.')
[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine('## Support tiers')
[void]$markdownBuilder.AppendLine()
foreach ($tier in $validTiers) {
    [void]$markdownBuilder.AppendLine("- **$tier** — $($manifest.tiers.$tier)")
}

$features = @($manifest.features | Sort-Object category, name, id)
foreach ($category in @($features.category | Sort-Object -Unique)) {
    [void]$markdownBuilder.AppendLine()
    [void]$markdownBuilder.AppendLine("## $category")
    [void]$markdownBuilder.AppendLine()
    [void]$markdownBuilder.AppendLine('| Feature | Status | Tier | Contract | Proof tests |')
    [void]$markdownBuilder.AppendLine('| --- | --- | --- | --- | --- |')
    foreach ($feature in @($features | Where-Object category -eq $category)) {
        $proofs = if (@($feature.proofTests).Count -eq 0) { '—' } else { @($feature.proofTests) -join ', ' }
        [void]$markdownBuilder.AppendLine("| $(Escape-MarkdownCell $feature.name) | $($feature.status) | $($feature.tier) | $(Escape-MarkdownCell $feature.summary) | $(Escape-MarkdownCell $proofs) |")
    }
}

[void]$markdownBuilder.AppendLine()
[void]$markdownBuilder.AppendLine("Manifest rows: $($features.Count).")
$generatedMarkdown = $markdownBuilder.ToString().Replace("`r`n", "`n")

$htmlBuilder = [Text.StringBuilder]::new(131072)
Add-HtmlLine $htmlBuilder '<!DOCTYPE html>'
Add-HtmlLine $htmlBuilder '<html lang="en" data-theme="dark">'
Add-HtmlLine $htmlBuilder '<head>'
Add-HtmlLine $htmlBuilder '    <meta charset="UTF-8">'
Add-HtmlLine $htmlBuilder '    <meta name="viewport" content="width=device-width, initial-scale=1.0">'
Add-HtmlLine $htmlBuilder '    <link rel="stylesheet" href="../css/style.css">'
Add-HtmlLine $htmlBuilder '    <link rel="preload" href="../js/csharpdb.bundle.js" as="script">'
Add-HtmlLine $htmlBuilder '    <title>EF Core Compatibility - CSharpDB</title>'
Add-HtmlLine $htmlBuilder '    <meta name="description" content="Evidence-backed EF Core provider compatibility matrix for CSharpDB, including support tiers, exact feature contracts, and automated proof tests.">'
Add-HtmlLine $htmlBuilder '    <link rel="canonical" href="https://csharpdb.com/docs/ef-core-compatibility.html">'
Add-HtmlLine $htmlBuilder '    <meta property="og:title" content="CSharpDB EF Core Compatibility">'
Add-HtmlLine $htmlBuilder '    <meta property="og:description" content="Evidence-backed compatibility contracts for the CSharpDB EF Core provider.">'
Add-HtmlLine $htmlBuilder '    <meta property="og:url" content="https://csharpdb.com/docs/ef-core-compatibility.html">'
Add-HtmlLine $htmlBuilder '    <meta property="og:image" content="https://csharpdb.com/images/og-banner.png">'
Add-HtmlLine $htmlBuilder '    <link rel="icon" type="image/png" href="../favicon.png">'
Add-HtmlLine $htmlBuilder '    <style>'
Add-HtmlLine $htmlBuilder '        .ef-maturity { margin: 24px 0; padding: 22px; border: 1px solid rgba(34, 197, 94, .45); border-radius: var(--radius-md); background: rgba(34, 197, 94, .08); }'
Add-HtmlLine $htmlBuilder '        .ef-maturity h2 { margin: 0 0 10px; color: #22c55e; }'
Add-HtmlLine $htmlBuilder '        .ef-meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; margin: 18px 0; }'
Add-HtmlLine $htmlBuilder '        .ef-meta > div { padding: 10px 12px; border: 1px solid var(--border); border-radius: var(--radius-sm); }'
Add-HtmlLine $htmlBuilder '        .ef-meta span { display: block; color: var(--text-muted); font-size: .74rem; }'
Add-HtmlLine $htmlBuilder '        .ef-tier-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px; margin: 18px 0; }'
Add-HtmlLine $htmlBuilder '        .ef-tier-card { padding: 16px; border: 1px solid var(--border); border-radius: var(--radius-sm); background: var(--bg-card); }'
Add-HtmlLine $htmlBuilder '        .ef-tier-card h3 { margin: 0 0 8px; }'
Add-HtmlLine $htmlBuilder '        .ef-toolbar { display: grid; grid-template-columns: minmax(240px, 2fr) minmax(160px, 1fr) minmax(140px, 1fr); gap: 12px; margin: 28px 0 16px; }'
Add-HtmlLine $htmlBuilder '        .ef-toolbar input, .ef-toolbar select { width: 100%; padding: 10px 12px; color: var(--text-primary); background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-sm); }'
Add-HtmlLine $htmlBuilder '        .ef-category { margin-top: 32px; }'
Add-HtmlLine $htmlBuilder '        .ef-category[hidden], .ef-feature-row[hidden] { display: none; }'
Add-HtmlLine $htmlBuilder '        .ef-table-wrap { overflow-x: auto; border: 1px solid var(--border); border-radius: var(--radius-md); }'
Add-HtmlLine $htmlBuilder '        .ef-table { width: 100%; min-width: 880px; margin: 0; border-collapse: collapse; }'
Add-HtmlLine $htmlBuilder '        .ef-table th, .ef-table td { padding: 14px; vertical-align: top; border-bottom: 1px solid var(--border); text-align: left; }'
Add-HtmlLine $htmlBuilder '        .ef-table tbody tr:last-child td { border-bottom: 0; }'
Add-HtmlLine $htmlBuilder '        .ef-feature-name { display: block; margin-bottom: 4px; font-weight: 700; }'
Add-HtmlLine $htmlBuilder '        .ef-feature-id { color: var(--text-muted); font-family: var(--font-mono); font-size: .75rem; }'
Add-HtmlLine $htmlBuilder '        .ef-badge { display: inline-block; padding: 3px 9px; border-radius: 999px; font-size: .72rem; font-weight: 700; text-transform: uppercase; letter-spacing: .04em; white-space: nowrap; }'
Add-HtmlLine $htmlBuilder '        .ef-badge-supported { color: #22c55e; background: rgba(34, 197, 94, .13); }'
Add-HtmlLine $htmlBuilder '        .ef-badge-partial { color: #f59e0b; background: rgba(245, 158, 11, .13); }'
Add-HtmlLine $htmlBuilder '        .ef-badge-unsupported { color: #ef4444; background: rgba(239, 68, 68, .13); }'
Add-HtmlLine $htmlBuilder '        .ef-badge-planned { color: var(--info); background: rgba(59, 130, 246, .13); }'
Add-HtmlLine $htmlBuilder '        .ef-tier { font-family: var(--font-mono); white-space: nowrap; }'
Add-HtmlLine $htmlBuilder '        .ef-proof-list { margin: 8px 0 0; padding-left: 18px; }'
Add-HtmlLine $htmlBuilder '        .ef-proof-list code { overflow-wrap: anywhere; }'
Add-HtmlLine $htmlBuilder '        @media (max-width: 720px) { .ef-toolbar { grid-template-columns: 1fr; } }'
Add-HtmlLine $htmlBuilder '    </style>'
Add-HtmlLine $htmlBuilder '</head>'
Add-HtmlLine $htmlBuilder '<body>'
Add-HtmlLine $htmlBuilder '    <script>'
Add-HtmlLine $htmlBuilder "        window.currentPage = 'docs'; window.pagePathPrefix = '../';"
Add-HtmlLine $htmlBuilder "        window.pageConfig = { title: 'CSharpDB EF Core Compatibility', description: 'Evidence-backed compatibility contracts for the CSharpDB EF Core provider.', keywords: 'CSharpDB EF Core compatibility, provider support matrix, Entity Framework Core', canonicalPath: 'docs/ef-core-compatibility.html', ogType: 'article' };"
Add-HtmlLine $htmlBuilder '    </script>'
Add-HtmlLine $htmlBuilder '    <div id="site-nav"></div>'
Add-HtmlLine $htmlBuilder '    <main class="page">'
Add-HtmlLine $htmlBuilder '        <div class="container doc-container">'
Add-HtmlLine $htmlBuilder '            <div class="doc-content full-width">'
Add-HtmlLine $htmlBuilder '                <h1>EF Core Compatibility</h1>'
Add-HtmlLine $htmlBuilder "                <p class=`"lead`">Evidence-backed feature contracts for <code>$(ConvertTo-HtmlText $manifest.provider)</code> against EF Core $(ConvertTo-HtmlText $manifest.efCoreVersion).</p>"
Add-HtmlLine $htmlBuilder '                <div class="ef-maturity">'
Add-HtmlLine $htmlBuilder "                    <h2>$(ConvertTo-HtmlText $manifest.maturity.designation)</h2>"
Add-HtmlLine $htmlBuilder "                    <p>$(ConvertTo-HtmlText $manifest.maturity.scope)</p>"
Add-HtmlLine $htmlBuilder "                    <p><strong>Tier 2:</strong> $(ConvertTo-HtmlText $manifest.maturity.tier2Policy)</p>"
Add-HtmlLine $htmlBuilder "                    <p><strong>Tier 3:</strong> $(ConvertTo-HtmlText $manifest.maturity.tier3Policy)</p>"
Add-HtmlLine $htmlBuilder '                </div>'
Add-HtmlLine $htmlBuilder '                <p>The designation is deliberately scoped: every row retains its own status and exact contract. A <strong>Partial</strong> row is qualified only inside its stated boundary, and a <strong>Planned</strong> row is not available today.</p>'
Add-HtmlLine $htmlBuilder '                <div class="ef-meta">'
Add-HtmlLine $htmlBuilder "                    <div><span>Provider</span><code>$(ConvertTo-HtmlText $manifest.provider)</code></div>"
Add-HtmlLine $htmlBuilder "                    <div><span>Qualified EF Core version</span>$(ConvertTo-HtmlText $manifest.efCoreVersion)</div>"
Add-HtmlLine $htmlBuilder "                    <div><span>Manifest rows</span>$($features.Count)</div>"
Add-HtmlLine $htmlBuilder '                </div>'
Add-HtmlLine $htmlBuilder '                <p>Read the <a href="entity-framework-core.html">provider guide</a> for setup and usage, then use this generated matrix as the authoritative public support boundary. The versioned <a href="https://github.com/MaxAkbar/CSharpDB/blob/main/docs/ef-core-compatibility.json">manifest JSON</a> and <a href="https://github.com/MaxAkbar/CSharpDB/blob/main/docs/ef-core-compatibility.schema.json">JSON Schema</a> remain the machine-readable sources.</p>'
Add-HtmlLine $htmlBuilder '                <h2>Support tiers</h2>'
Add-HtmlLine $htmlBuilder '                <div class="ef-tier-grid">'
foreach ($tier in $validTiers) {
    $tierNumber = $tier.Substring(4)
    Add-HtmlLine $htmlBuilder '                    <div class="ef-tier-card">'
    Add-HtmlLine $htmlBuilder "                        <h3>Tier $(ConvertTo-HtmlText $tierNumber)</h3>"
    Add-HtmlLine $htmlBuilder "                        <p>$(ConvertTo-HtmlText $manifest.tiers.$tier)</p>"
    Add-HtmlLine $htmlBuilder '                    </div>'
}
Add-HtmlLine $htmlBuilder '                </div>'
Add-HtmlLine $htmlBuilder '                <div class="ef-toolbar" aria-label="EF Core compatibility filters">'
Add-HtmlLine $htmlBuilder '                    <label><span class="sr-only">Search features</span><input id="ef-search" type="search" placeholder="Search feature, contract, or proof test"></label>'
Add-HtmlLine $htmlBuilder '                    <label><span class="sr-only">Filter status</span><select id="ef-status"><option value="">All statuses</option><option value="supported">Supported</option><option value="partial">Partial</option><option value="unsupported">Unsupported</option><option value="planned">Planned</option></select></label>'
Add-HtmlLine $htmlBuilder '                    <label><span class="sr-only">Filter tier</span><select id="ef-tier"><option value="">All tiers</option><option value="tier1">Tier 1</option><option value="tier2">Tier 2</option><option value="tier3">Tier 3</option></select></label>'
Add-HtmlLine $htmlBuilder '                </div>'
Add-HtmlLine $htmlBuilder "                <p id=`"ef-visible-count`" aria-live=`"polite`">Showing $($features.Count) feature rows.</p>"

foreach ($category in @($features.category | Sort-Object -Unique)) {
    Add-HtmlLine $htmlBuilder '                <section class="ef-category">'
    Add-HtmlLine $htmlBuilder "                    <h2>$(ConvertTo-HtmlText $category)</h2>"
    Add-HtmlLine $htmlBuilder '                    <div class="ef-table-wrap">'
    Add-HtmlLine $htmlBuilder '                        <table class="ef-table">'
    Add-HtmlLine $htmlBuilder '                            <thead><tr><th scope="col">Feature</th><th scope="col">Status</th><th scope="col">Tier</th><th scope="col">Contract and evidence</th></tr></thead>'
    Add-HtmlLine $htmlBuilder '                            <tbody>'
    foreach ($feature in @($features | Where-Object category -eq $category)) {
        $statusToken = ConvertTo-CssToken ([string]$feature.status)
        $tierToken = ConvertTo-CssToken ([string]$feature.tier)
        $searchText = "$($feature.id) $($feature.category) $($feature.name) $($feature.status) $($feature.tier) $($feature.summary) $(@($feature.proofTests) -join ' ')".ToLowerInvariant()
        Add-HtmlLine $htmlBuilder "                                <tr class=`"ef-feature-row`" id=`"feature-$(ConvertTo-HtmlText $feature.id)`" data-status=`"$(ConvertTo-HtmlText $statusToken)`" data-tier=`"$(ConvertTo-HtmlText $tierToken)`" data-search=`"$(ConvertTo-HtmlText $searchText)`">"
        Add-HtmlLine $htmlBuilder "                                    <td><span class=`"ef-feature-name`">$(ConvertTo-HtmlText $feature.name)</span><span class=`"ef-feature-id`">$(ConvertTo-HtmlText $feature.id)</span></td>"
        Add-HtmlLine $htmlBuilder "                                    <td><span class=`"ef-badge ef-badge-$statusToken`">$(ConvertTo-HtmlText $feature.status)</span></td>"
        Add-HtmlLine $htmlBuilder "                                    <td><span class=`"ef-tier`">Tier $(ConvertTo-HtmlText ([string]$feature.tier).Substring(4))</span></td>"
        Add-HtmlLine $htmlBuilder '                                    <td>'
        Add-HtmlLine $htmlBuilder "                                        <p>$(ConvertTo-HtmlText $feature.summary)</p>"
        if (@($feature.proofTests).Count -gt 0) {
            Add-HtmlLine $htmlBuilder "                                        <details><summary>$(@($feature.proofTests).Count) automated proof test(s)</summary>"
            Add-HtmlLine $htmlBuilder '                                            <ul class="ef-proof-list">'
            foreach ($proofTest in @($feature.proofTests)) {
                Add-HtmlLine $htmlBuilder "                                                <li><code>$(ConvertTo-HtmlText $proofTest)</code></li>"
            }
            Add-HtmlLine $htmlBuilder '                                            </ul>'
            Add-HtmlLine $htmlBuilder '                                        </details>'
        }
        else {
            Add-HtmlLine $htmlBuilder '                                        <p><em>No automated proof is claimed for this unavailable or planned row.</em></p>'
        }
        Add-HtmlLine $htmlBuilder '                                    </td>'
        Add-HtmlLine $htmlBuilder '                                </tr>'
    }
    Add-HtmlLine $htmlBuilder '                            </tbody>'
    Add-HtmlLine $htmlBuilder '                        </table>'
    Add-HtmlLine $htmlBuilder '                    </div>'
    Add-HtmlLine $htmlBuilder '                </section>'
}

Add-HtmlLine $htmlBuilder '            </div>'
Add-HtmlLine $htmlBuilder '        </div>'
Add-HtmlLine $htmlBuilder '    </main>'
Add-HtmlLine $htmlBuilder '    <div id="site-footer"></div>'
Add-HtmlLine $htmlBuilder '    <script>'
Add-HtmlLine $htmlBuilder '        (() => {'
Add-HtmlLine $htmlBuilder "            const rows = [...document.querySelectorAll('.ef-feature-row')];"
Add-HtmlLine $htmlBuilder "            const sections = [...document.querySelectorAll('.ef-category')];"
Add-HtmlLine $htmlBuilder "            const search = document.getElementById('ef-search');"
Add-HtmlLine $htmlBuilder "            const status = document.getElementById('ef-status');"
Add-HtmlLine $htmlBuilder "            const tier = document.getElementById('ef-tier');"
Add-HtmlLine $htmlBuilder "            const count = document.getElementById('ef-visible-count');"
Add-HtmlLine $htmlBuilder '            const apply = () => {'
Add-HtmlLine $htmlBuilder '                const query = search.value.trim().toLowerCase();'
Add-HtmlLine $htmlBuilder '                let visible = 0;'
Add-HtmlLine $htmlBuilder '                for (const row of rows) {'
Add-HtmlLine $htmlBuilder '                    const show = (!query || row.dataset.search.includes(query)) && (!status.value || row.dataset.status === status.value) && (!tier.value || row.dataset.tier === tier.value);'
Add-HtmlLine $htmlBuilder '                    row.hidden = !show;'
Add-HtmlLine $htmlBuilder '                    if (show) visible++;'
Add-HtmlLine $htmlBuilder '                }'
Add-HtmlLine $htmlBuilder "                for (const section of sections) section.hidden = !section.querySelector('.ef-feature-row:not([hidden])');"
Add-HtmlLine $htmlBuilder '                count.textContent = `Showing ${visible} feature row${visible === 1 ? '''' : ''s''}.`;'
Add-HtmlLine $htmlBuilder '            };'
Add-HtmlLine $htmlBuilder "            search.addEventListener('input', apply);"
Add-HtmlLine $htmlBuilder "            status.addEventListener('change', apply);"
Add-HtmlLine $htmlBuilder "            tier.addEventListener('change', apply);"
Add-HtmlLine $htmlBuilder '        })();'
Add-HtmlLine $htmlBuilder '    </script>'
Add-HtmlLine $htmlBuilder '    <script src="../js/csharpdb.bundle.js" defer></script>'
Add-HtmlLine $htmlBuilder '</body>'
Add-HtmlLine $htmlBuilder '</html>'

$generatedHtml = $htmlBuilder.ToString().Replace("`r`n", "`n")

if ($Check) {
    foreach ($generatedArtifact in @(
        @{ Path = $markdownOutputPath; Content = $generatedMarkdown; Name = 'Markdown document' },
        @{ Path = $htmlOutputPath; Content = $generatedHtml; Name = 'website page' }
    )) {
        if (-not (Test-Path -LiteralPath $generatedArtifact.Path -PathType Leaf)) {
            throw "Generated EF Core compatibility $($generatedArtifact.Name) is missing. Run scripts/Build-EfCoreCompatibility.ps1."
        }
        $existing = [IO.File]::ReadAllText($generatedArtifact.Path).Replace("`r`n", "`n")
        if (-not [string]::Equals($existing, $generatedArtifact.Content, [StringComparison]::Ordinal)) {
            throw "Generated EF Core compatibility $($generatedArtifact.Name) is stale. Run scripts/Build-EfCoreCompatibility.ps1."
        }
    }
    Write-Host "EF Core compatibility Markdown and HTML are current ($($features.Count) feature rows)."
    return
}

[IO.File]::WriteAllText($markdownOutputPath, $generatedMarkdown, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText($htmlOutputPath, $generatedHtml, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $markdownOutputPath and $htmlOutputPath from $manifestPath ($($features.Count) feature rows)."
