using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace CSharpDB.Observability;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    GenerationMode = JsonSourceGenerationMode.Metadata,
    UseStringEnumConverter = true)]
[JsonSerializable(typeof(CSharpDbObservabilityOptions))]
[JsonSerializable(typeof(CSharpDbLoggingOptions))]
[JsonSerializable(typeof(Dictionary<CSharpDbOperationClass, TimeSpan>))]
[JsonSerializable(typeof(CSharpDbHistoryOptions))]
[JsonSerializable(typeof(CSharpDbOpenTelemetryOptions))]
[JsonSerializable(typeof(CSharpDbOpenTelemetryResourceOptions))]
[JsonSerializable(typeof(CSharpDbOtlpOptions))]
[JsonSerializable(typeof(CSharpDbConsoleExporterOptions))]
[JsonSerializable(typeof(CSharpDbPrometheusOptions))]
[JsonSerializable(typeof(CSharpDbHealthOptions))]
[JsonSerializable(typeof(QueryFingerprint))]
[JsonSerializable(typeof(QueryFingerprintResult))]
[JsonSerializable(typeof(OpaqueDiagnosticsId))]
[JsonSerializable(typeof(DiagnosticsTraceId))]
[JsonSerializable(typeof(SafeErrorProjection))]
[JsonSerializable(typeof(CSharpDbOperationContext))]
[JsonSerializable(typeof(CSharpDbQueryCompletedEvent))]
[JsonSerializable(typeof(CSharpDbSlowQueryEvent))]
[JsonSerializable(typeof(CSharpDbQueryFailedEvent))]
[JsonSerializable(typeof(CSharpDbQueryCanceledEvent))]
[JsonSerializable(typeof(CSharpDbLongRunningQueryEvent))]
[JsonSerializable(typeof(CSharpDbHostStartingEvent))]
[JsonSerializable(typeof(CSharpDbRawSqlCaptureEnabledEvent))]
[JsonSerializable(typeof(CSharpDbLifecycleCompletedEvent))]
[JsonSerializable(typeof(CSharpDbHealthTransitionEvent))]
[JsonSerializable(typeof(CSharpDbApiErrorEvent))]
[JsonSerializable(typeof(DiagnosticsSnapshotMetadata))]
[JsonSerializable(typeof(RuntimeDiagnosticsSnapshot))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<RuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<RuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<RuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(QueryDiagnosticsSummary))]
[JsonSerializable(typeof(ShardDiagnosticsSection<QueryDiagnosticsSummary>))]
[JsonSerializable(typeof(ActiveQuerySnapshot))]
[JsonSerializable(typeof(ActiveQuerySnapshot[]))]
[JsonSerializable(typeof(BoundedDiagnosticsSnapshot<ActiveQuerySnapshot>))]
[JsonSerializable(typeof(DiagnosticsCollectionSnapshot<ActiveQuerySnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsCollectionSnapshot<ActiveQuerySnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsCollectionSnapshot<ActiveQuerySnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsCollectionSnapshot<ActiveQuerySnapshot>>))]
[JsonSerializable(typeof(RecentQuerySnapshot))]
[JsonSerializable(typeof(RecentQuerySnapshot[]))]
[JsonSerializable(typeof(BoundedDiagnosticsSnapshot<RecentQuerySnapshot>))]
[JsonSerializable(typeof(DiagnosticsCollectionSnapshot<RecentQuerySnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsCollectionSnapshot<RecentQuerySnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsCollectionSnapshot<RecentQuerySnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsCollectionSnapshot<RecentQuerySnapshot>>))]
[JsonSerializable(typeof(QueryDetailSnapshot))]
[JsonSerializable(typeof(DiagnosticsValueSnapshot<QueryDetailSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsValueSnapshot<QueryDetailSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsValueSnapshot<QueryDetailSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsValueSnapshot<QueryDetailSnapshot>>))]
[JsonSerializable(typeof(QueryPlanDiagnosticsSnapshot))]
[JsonSerializable(typeof(DiagnosticsValueSnapshot<QueryPlanDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsValueSnapshot<QueryPlanDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsValueSnapshot<QueryPlanDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsValueSnapshot<QueryPlanDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<QueryPlanDiagnosticsSnapshot>))]
[JsonSerializable(typeof(ConnectionDiagnosticsSnapshot))]
[JsonSerializable(typeof(ShardDiagnosticsSection<ConnectionDiagnosticsSnapshot>))]
[JsonSerializable(typeof(SessionDiagnosticsSnapshot))]
[JsonSerializable(typeof(SessionDiagnosticsSnapshot[]))]
[JsonSerializable(typeof(BoundedDiagnosticsSnapshot<SessionDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsCollectionSnapshot<SessionDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsCollectionSnapshot<SessionDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsCollectionSnapshot<SessionDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsCollectionSnapshot<SessionDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(StorageRuntimeDiagnosticsSnapshot))]
[JsonSerializable(typeof(StorageCacheDiagnosticsSnapshot))]
[JsonSerializable(typeof(StorageDeviceIoDiagnosticsSnapshot))]
[JsonSerializable(typeof(DiagnosticsValueSnapshot<StorageRuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsValueSnapshot<StorageRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsValueSnapshot<StorageRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsValueSnapshot<StorageRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(WalRuntimeDiagnosticsSnapshot))]
[JsonSerializable(typeof(DiagnosticsValueSnapshot<WalRuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsValueSnapshot<WalRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsValueSnapshot<WalRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsValueSnapshot<WalRuntimeDiagnosticsSnapshot>>))]
[JsonSerializable(typeof(WalRecoveryDiagnosticsSnapshot))]
[JsonSerializable(typeof(CheckpointDiagnosticsSnapshot))]
[JsonSerializable(typeof(MaintenanceOperationSnapshot))]
[JsonSerializable(typeof(MaintenanceOperationSnapshot[]))]
[JsonSerializable(typeof(BoundedDiagnosticsSnapshot<MaintenanceOperationSnapshot>))]
[JsonSerializable(typeof(DiagnosticsCollectionSnapshot<MaintenanceOperationSnapshot>))]
[JsonSerializable(typeof(DiagnosticsTopologySnapshot<DiagnosticsCollectionSnapshot<MaintenanceOperationSnapshot>>))]
[JsonSerializable(typeof(RuntimeDiagnosticsFamilySection<DiagnosticsCollectionSnapshot<MaintenanceOperationSnapshot>>))]
[JsonSerializable(typeof(ShardDiagnosticsSection<DiagnosticsCollectionSnapshot<MaintenanceOperationSnapshot>>))]
[JsonSerializable(typeof(HealthDiagnosticsSnapshot))]
[JsonSerializable(typeof(CSharpDbHostStateSnapshot))]
[JsonSerializable(typeof(DiagnosticsSection<QueryDiagnosticsSummary>))]
[JsonSerializable(typeof(DiagnosticsSection<ConnectionDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<StorageRuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<StorageCacheDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<StorageDeviceIoDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<WalRuntimeDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<WalRecoveryDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<CheckpointDiagnosticsSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<MaintenanceOperationSnapshot>))]
[JsonSerializable(typeof(DiagnosticsSection<HealthDiagnosticsSnapshot>))]
public sealed partial class CSharpDbObservabilityJsonContext : JsonSerializerContext
{
    // The .NET 10 string-enum reader uses Regex on its deserialization path.
    // Preserve that optional framework dependency when this context is used
    // from a fully trimmed managed application.
    [DynamicDependency(nameof(Regex.InfiniteMatchTimeout), typeof(Regex))]
    static CSharpDbObservabilityJsonContext()
    {
    }
}
